version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - server_data:/app/instance
      - ./server/ids.db:/app/ids.db
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=http://127.0.0.1:5000
    volumes:
      - /var/log/journal:/var/log/journal:ro
      - /var/log:/var/log:ro
      - /etc/machine-id:/etc/machine-id:ro
    privileged: true
    network_mode: "host"
    restart: always
    depends_on:
      - server

volumes:
  server_data:
